version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: msvc_rents
    networks:
      - msvc
    volumes:
      - data-mysql:/var/lib/mysqls

  msvc_rent:
    container_name: msvc_rents
    image: apolos7/rent:latest
    ports:
      - "8004:8004"
    environment:
      PORT: 8004
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_rents
      DB_USERNAME: root
      DB_PASSWORD: 1234
    networks:
      - msvc
    depends_on:
      - mysql8
    restart: always

volumes:
  data-mysql:
    name: data-mysql

networks:
  msvc:
    name: msvc